#GitHub actio part1 Basics
#
#by VE
name: MyGithubActionsBasics
env:
  application_name: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-version-${{ github.sha }}"

on:
  push:
    branches:
      - main
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    
    steps:
     - name: Print Hello Message
       run: echo "Hello World from Testing Job"
     - name: Execute few commands
       run : |
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name: ${{ env.application_name }}"          
          
     - name: Git clone by repo
       uses: actions/checkout@v1
     
     - name: List current folder
       run: ls -la
  
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is Job leve Variable1"
    steps:
     - name: Print Hello Message
       run: echo "Hello World from Deploy Job"
       
     - name: Printing deployment package
       run : echo "Deploy package name is ${{ env. DEPLOY_PACKAGE_NAME }} "
    
    
    
    
